// file-loader modules
declare module '*.png';
declare module '*.svg';
declare module '*.jpg';
declare module '*.gif';
declare module '*.mp4';
declare module '*.mp3';
declare module '*.html';
declare module '*.css';
